version: 0.2

phases:
  pre_build:
    commands:
      - echo 'Logging into AWS'
      - aws --version
      - REPOSITORY_URI=560773393352.dkr.ecr.us-east-2.amazonaws.com
      
#      - $(aws ecr get-login --region us-east-2 --registry-ids 732631625641)
#      - $(aws ecr get-login-password --region us-east-2)
#      - aws ecr get-authorization-token  --region us-east-2 | sed 's|https://||'
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - cd java-micro-service-projects
      - mvn install
      - cd account-service
      - docker build . -t $REPOSITORY_URI/ss-cloud-poc:account-service-1.0
      - docker push       $REPOSITORY_URI/ss-cloud-poc:account-service-1.0
      - cd ..
      - cd customer-service
      - docker build . -t $REPOSITORY_URI/ss-cloud-poc:customer-service-1.0
      - docker push       $REPOSITORY_URI/ss-cloud-poc:customer-service-1.0
      -
      - docker pull lucascoelhocs/db-derby:latest
      - docker tag  lucascoelhocs/db-derby:latest  $REPOSITORY_URI/ss-cloud-poc:db-derby-1.0
      - docker push $REPOSITORY_URI/ss-cloud-poc:db-derby-1.0
      -
      - cd ../..
      - cd python_websvc
      - docker build . -t $REPOSITORY_URI/ss-cloud-poc:loan-service-1.0
      - docker push       $REPOSITORY_URI/ss-cloud-poc:loan-service-1.0
      - 
      - cd ..
      - aws s3 cp kubernetes-manifests/account-depl.yaml         s3://ss-poc-shibu/
      - aws s3 cp kubernetes-manifests/account-service.yaml      s3://ss-poc-shibu/
      - aws s3 cp kubernetes-manifests/customer-depl.yaml        s3://ss-poc-shibu/
      - aws s3 cp kubernetes-manifests/customer-service.yaml     s3://ss-poc-shibu/
      - aws s3 cp kubernetes-manifests/derby-db-depl.yaml        s3://ss-poc-shibu/
      - aws s3 cp kubernetes-manifests/derby-db-service.yaml     s3://ss-poc-shibu/
      - aws s3 cp kubernetes-manifests/loan-depl.yaml            s3://ss-poc-shibu/
      - aws s3 cp kubernetes-manifests/loan-service.yaml         s3://ss-poc-shibu/
