version: 0.2

phases:
  pre_build:
    commands:
  build:
    commands:
      - aws cloudformation create-stack --stack-name daytrader-app-stack --template-url ile://daytrader-api-gateway-nested-stack.yml --capabilities CAPABILITY_IAM --region us-east-2
