version: 0.2

phases:
  pre_build:
    commands:
  build:
    commands:
      - aws cloudformation create-stack --stack-name daytrader-app-stack --template-body file://daytrader-api-gateway-nested-stack.yml --parameters ParameterKey=daytradeURI,ParameterValue=https://20.54.182.253 --capabilities CAPABILITY_IAM --region us-east-2
